//mutations函数名称得模块接收
export const RECEIVE_TAGLIST = 'receive_tagList'
export const RECEIVE_FOCUSLIST = 'receive_focusList'
export const RECEIVE_POLICYDESCLIST = 'receive_policyDescList'
export const RECEIVE_KINGKONGLIST = 'receive_kingKongList'
export const RECEIVE_INDEXACTIVITYMODULE = 'receive_indexActivityModule'
export const RECEIVE_CATEGORYL1LIST = 'receive_categoryL1List'
export const RECEIVE_CATELIST = 'receive_cateList'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_CATEGORYL2LIST = 'receive_categoryL2List'
export const RECEIVE_GETTABS = 'receive-getTabs'
export const RECEIVE_RECMANUAL = 'receive_recManual'
export const RECEIVE_RECAUTO = 'receive_recAuto'
